### ISSUE TITLE
missing dependencies with some releases of alvisnlp

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/alvisnlp#102]
working with alvisnlp v 0.5 (tag 0.5) to create a conda package and it doesn't compile with maven. I think it's because some dependencies have changed. Have the following error : 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project alvisnlp-core: Compilation failure
[ERROR] Annotation processor 'org.bibliome.util.service.ServiceAnnotationProcessor' not found

**Comment by rbossy** [comment]
0.5 uses a deprecated version of the [bibliome-java-utils](https://github.com/Bibliome/bibliome-java-utils).

You could dig the right commit, name it as a release, etc.

But I would suggest using the master head of alvisnlp.
