### ISSUE TITLE
Tabular Export and OutputDir

### ISSUE THREAD

**Issue by ldeleger** [Bibliome/alvisnlp#106]
The TabularExport module does not take into account the `-outputDir` command line parameter when `<trueCSV/>` is specified.

**Comment by rbossy** [comment]
Fix in c18d8c6889c0e52c7121ed4d3efcec1c46db1d08

**Comment by rbossy** [comment]
Seems to work, right @ldeleger ?

**Comment by ldeleger** [comment]
Yes :)
