### ISSUE TITLE
Check params of module YateaExtractor

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/alvisnlp#114]
Check error caused by the following params of module YateaExtractor. They are documented as optional but handled as mandatory by AlvisNLP during execution. 
* localeDir
* configDir

See Yatea module doc : https://bibliome.github.io/alvisnlp/reference/module/YateaExtractor

**Comment by rbossy** [comment]
@mandiayba please use the module full name in the title of issues, please.

**Comment by rbossy** [comment]
Fixed in c8b89a2522d5a4548c9e15c90e1130ba980ffced

Please test @mandiayba
