### ISSUE TITLE
Drop OpenMinTeD support

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#134]
Remove the following command-line options:

- `--input`
- `--output`
- `--param`

**Comment by mandiayba** [comment]
Je pense effectivement qu'il faut supprimer, ils sont redondants...

Le jeu. 16 déc. 2021 à 12:20, Robert Bossy ***@***.***> a
écrit :

**Comment by rbossy** [comment]
7f8dd526982fafd1364f392ecc585c8e3dd1c616 and 0ca15b793f819fe13c40e3091d354e8e7eedfad9
