### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by marinecourtin** [Bibliome/alvisnlp#157]
In the [documentation of the BioNLPSTReader module](https://github.com/Bibliome/alvisnlp/blob/master/docs/reference/module/BioNLPSTReader.md) the link for the description of the  BioNLP-ST 2013 a1/a2 format is broken.

I found a description of the format [here](https://2013.bionlp-st.org/file-formats)

**Comment by rbossy** [comment]
fixed in 554a44c updated docs in ab70aa7
