### ISSUE TITLE
SimpleProjector2 ne projette pas sur les premiers termes d'un abstract

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#16]
[Redmine issue](https://migale.jouy.inra.fr/redmine/issues/7480).

**Comment by EstelleChaix** [comment]
-> Pas de PMID : l'abstract est dans corpus2000_12012017.txt  ligne 63307
Je ne sais pas comment est créé le DocID avec WebOfKnowledgeReader 
-> J'ai reproduis l'erreur requête :  http://bibliome.jouy.inra.fr/demo/seedev/alvisir/webapi/search?q=ABI3+complementation+of+seed+maturation
-> Et j'ai rajouté la colonne dans output/entities.txt

**Comment by phatonin** [comment]
Bug chez [bibliome-java-utils](https://github.com/Bibliome/bibliome-java-utils), résolu avec e562269a7ac2a9b2e705ac10ffc1b317bc35e651 .

**Comment by rbossy** [comment]
Bug chez [bibliome-java-utils](https://github.com/Bibliome/bibliome-java-utils), résolu avec [e562269a7ac2a9b2e705ac10ffc1b317bc35e651](https://github.com/Bibliome/bibliome-java-utils/commit/e562269a7ac2a9b2e705ac10ffc1b317bc35e651) .
