### ISSUE TITLE
Docker dist

### ISSUE THREAD

**Issue by jibe-b** [Bibliome/alvisnlp#26]
Providing packaged docker would enable to install easily AlvisNLP.

**Comment by mandiayba** [comment]
A test version is available in docker (#alvisengine). A complete version is under development.

**Comment by rbossy** [comment]
To be useful, the dock should include third-party software for the following modules:

* `Species`
* `BioLG`
* `CCGParser`
* `CCGPosTagger`
* `EnjuParser`
* `EnjuParser2`
* `GeniaTagger`
* `StanfordNER`
* `TEESClassify`
* `TEESTrain`
* `TreeTagger`
* `WapitiLabel`
* `WapitiTrain`
* `YateaExtractor`

Java libs are handled by the POM.

**Comment by mandiayba** [comment]
Adding these tools to the alvis docker image - need the version and homepage for each third-party software. @rbossy

**Comment by rbossy** [comment]
* [Species](http://linnaeus.sourceforge.net/) 1.0
* [BioLG](http://mars.cs.utu.fi/biolg/) 1.1.12
* [CCGParser](http://www.cl.cam.ac.uk/~sc609/candc-1.00.html) 1.00
* [CCGPosTagger](http://www.cl.cam.ac.uk/~sc609/candc-1.00.html) 1.00
* [EnjuParser](http://www.nactem.ac.uk/enju/) 2.4.2
* [EnjuParser2](http://www.nactem.ac.uk/enju/) 2.4.2
* [GeniaTagger](http://www.nactem.ac.uk/GENIA/tagger/) 3.0.1^*
* [StanfordNER](https://nlp.stanford.edu/software/CRF-NER.shtml) 2014-06-16^*
* [TEESClassify](https://github.com/jbjorne/TEES/) 2.2.1
* [TEESTrain](https://github.com/jbjorne/TEES/) 2.2.1
* [TreeTagger](http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/) 3.2^*
* [WapitiLabel](https://wapiti.limsi.fr/) 1.5.0
* [WapitiTrain](https://wapiti.limsi.fr/) 1.5.0
* [YateaExtractor](https://perso.limsi.fr/hamon/YaTeA/) 0.5^*

^* Not the latest version, we might want to test with the latest version.

@mandiayba

**Comment by mandiayba** [comment]
in progress... follow here https://github.com/openminted/alvis-docker.git
