### ISSUE TITLE
TEES test

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#28]
Need a test for TEES. Otherwise merging `tees-code-review` will be risky...

**Comment by mandiayba** [comment]
issue with the test related to ASCII versus UTF8 text files : during execution the quote char (") is replaced by &quot; that causes TEES bug.

**Comment by rbossy** [comment]
Progress was made: 4838dd6095d29a35affcb80463958b66b011b0eb

**Comment by rbossy** [comment]
2b3ba1aeecdf612789f022ccbb1cf22c541f6a21
