### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by jibe-b** [Bibliome/alvisnlp#29]
[bibliome.org](http://bibliome.org) hence belongs to [BioFoundation](http://biofoundation.net/) so package naming org.bibliome.… may conflict with other.

We probably don't care as the contents date back to 2011, 2012.

**Comment by rbossy** [comment]
Renamed packages to `fr.inra.maiage.bibliome.*` in branch [`package-rename`](https://github.com/Bibliome/alvisnlp/tree/package-rename): b485a1cec03e5fb26c252be992be766a03a88020

## Important

Merging requires that the package renaming has been merged and exposed into Maven repo for [bibliome-java-utils](https://github.com/Bibliome/bibliome-java-utils/tree/package-rename) and [alvisir](https://github.com/Bibliome/alvisir/tree/package-rename).

**That may break installs**

**Comment by rbossy** [comment]
Renamed issue. Old title: **[convention] org.bibliome is a namespace associated with bibliome.org**

**Comment by rbossy** [comment]
Renamed base package name to `fr.inra.maiage.bibliome.alvisnlp`.

Branch: `package-rename` : b485a1cec03e5fb26c252be992be766a03a88020
