### ISSUE TITLE
Problem with AlvisNLP and Stanford NER new versions (>3.4)

### ISSUE THREAD

**Issue by ldeleger** [Bibliome/alvisnlp#30]
There is an error when trying to run AlvisNLP with new versions of Stanford NER (>3.4)
Example with stanford-ner-2016-10-31:

> Loading classifier from /bibdev/sources/stanford/stanford-ner-2016-10-31/classifiers/english.all.3class.distsim.crf.ser.gz ... Loading distsim lexicon from /u/nlp/data/pos_tags_are_useless/egw4-reut.512.clusters ... [2017-07-06 15:22:47.000][alvisnlp] SEVERE java.io.FileNotFoundException: /u/nlp/data/pos_tags_are_useless/egw4-reut.512.clusters (Aucun fichier ou dossier de ce type)

Error obtained when running: `/bibdev/install/alvisnlp/devel/bin/alvisnlp -verbose -log err.log /bibdev/travail/OpenMinted/UseCases/Wheat/uc-tdm-AS-D/plans/test-stanford.plan`

However, there is no problem running Stanford NER as a standalone tool:
```
$ java -mx600m -cp /bibdev/sources/stanford/stanford-ner-2016-10-31/stanford-ner.jar:/bibdev/sources/stanford/stanford-ner-2016-10-31/lib/* edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier /bibdev/sources/stanford/stanford-ner-2016-10-31/classifiers/english.all.3class.distsim.crf.ser.gz -textFile /bibdev/sources/stanford/stanford-ner-2016-10-31/sample.txt
Invoked on Thu Jul 06 15:17:01 CEST 2017 with arguments: -loadClassifier /bibdev/sources/stanford/stanford-ner-2016-10-31/classifiers/english.all.3class.distsim.crf.ser.gz -textFile /bibdev/sources/stanford/stanford-ner-2016-10-31/sample.txt
loadClassifier=/bibdev/sources/stanford/stanford-ner-2016-10-31/classifiers/english.all.3class.distsim.crf.ser.gz
textFile=/bibdev/sources/stanford/stanford-ner-2016-10-31/sample.txt
Loading classifier from /bibdev/sources/stanford/stanford-ner-2016-10-31/classifiers/english.all.3class.distsim.crf.ser.gz ... done [1,3 sec].
The/O fate/O of/O Lehman/ORGANIZATION Brothers/ORGANIZATION ,/O the/O beleaguered/O investment/O bank/O ,/O hung/O in/O the/O balance/O on/O Sunday/O as/O Federal/ORGANIZATION Reserve/ORGANIZATION officials/O and/O the/O leaders/O of/O major/O financial/O institutions/O continued/O to/O gather/O in/O emergency/O meetings/O trying/O to/O complete/O a/O plan/O to/O rescue/O the/O stricken/O bank/O ./O 
Several/O possible/O plans/O emerged/O from/O the/O talks/O ,/O held/O at/O the/O Federal/ORGANIZATION Reserve/ORGANIZATION Bank/ORGANIZATION of/ORGANIZATION New/ORGANIZATION York/ORGANIZATION and/O led/O by/O Timothy/PERSON R./PERSON Geithner/PERSON ,/O the/O president/O of/O the/O New/ORGANIZATION York/ORGANIZATION Fed/ORGANIZATION ,/O and/O Treasury/ORGANIZATION Secretary/O Henry/PERSON M./PERSON Paulson/PERSON Jr./PERSON ./O
```

**Comment by rbossy** [comment]
Can you try the following:

In AlvisNLP source, edit the file `bibliome/pom.xml`. Remove (or comment) the following dependency:

```
    <dependency>
      <groupId>edu.stanford.nlp</groupId>
      <artifactId>stanford-corenlp</artifactId>
      <version>3.6.0</version>
    </dependency>
```

Recompile, reinstall, test...

**Comment by ldeleger** [comment]
No, it doesn't work, I get the same error.
From what I could understand, when AlvisNLP is installed, it fetches some stanford files (jar, pom) from a maven repository which has version 3.4 and this might not be compatible with newer versions of Stanford NER (latest is 3.8 I think).

**Comment by rbossy** [comment]
@ldeleger 

In `bibliome/pom.xml`:

* Comment the Stanford NER dependency:

```
<dependency> <!-- Could it be the same as CoreNLP -->
      <groupId>edu.stanford.nlp</groupId>
      <artifactId>stanford-ner</artifactId>
      <version>3.4</version>
    </dependency>
```

* Uncomment the coreNLP dependency and update the version:

```
    <dependency>
      <groupId>edu.stanford.nlp</groupId>
      <artifactId>stanford-corenlp</artifactId>
      <version>3.8.0</version>
    </dependency>
```

This might work, but might also break everything. If it doesn't work, you'll have to use 3.4 classifiers until AlvisNLP is updated...

**Comment by ldeleger** [comment]
It works!
Although I get this warning: 
```
log4j:WARN No appenders could be found for logger (edu.stanford.nlp.ie.AbstractSequenceClassifier).
log4j:WARN Please initialize the log4j system properly.
```
Do you want me to make a commit+push of these changes?

**Comment by rbossy** [comment]
I suspect that this might break somehow `AlvisIRIndexer`. Do you have the means to index something and test?

**Comment by ldeleger** [comment]
I indexed some annotations, it seemed to work, the module did not complain. Should I try to visualize it in the search engine to be sure?

**Comment by ldeleger** [comment]
Tested on the Wheat search engine, looks ok!

**Comment by rbossy** [comment]
7fdd40fd8fb8bb820d86896746046f4bed3fd5e1
