### ISSUE TITLE
Data model diagram source

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#31]
In [[AlvisNLP-ML-data-model]], the diagram has a small mistake. Please insert the source in the wiki repo.

@mandiayba

**Comment by mandiayba** [comment]
Could you add a link to the concerned diagram ?

**Comment by rbossy** [comment]
https://raw.githubusercontent.com/wiki/Bibliome/alvisnlp/assets/alvis_data_model.png

**Comment by mandiayba** [comment]
I use draw.io and the editable diagram is here https://drive.google.com/file/d/0B_zu-oL4RSolbmNLOV9zemQ4Mlk/view?usp=sharing

**Comment by rbossy** [comment]
thx
