### ISSUE TITLE
alvisnlp releases

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/alvisnlp#32]
could you please add a release for alvisnlp at here https://github.com/Bibliome/alvisnlp/releases ?

**Comment by rbossy** [comment]
Ok. What for?

**Comment by mandiayba** [comment]
I am writing a conda receipt for alvisnlp. The skeleton example I use seems to require that information.

**Comment by rbossy** [comment]
https://github.com/Bibliome/alvisnlp/releases/tag/0.5
