### ISSUE TITLE
Chose a damn place for documentation

### ISSUE THREAD

**Issue by jibe-b** [Bibliome/alvisnlp#38]
Dans la documentation des modules (par ex. [Tbular export](http://bibliome.jouy.inra.fr/demo/alvisnlp/api/modules/TabularExport))

les liens vers la documentation des types dirigent vers une page 404 (du glassfish)

ex:
> fileName
> 
> Mandatory
> Type: **Expression**

**Comment by rbossy** [comment]
La doc de référence est à trois endroits différents et j'aimerais en choisir un:

1. [Avec l'API REST](http://bibliome.jouy.inra.fr/demo/alvisnlp/)
  * [-] isolé de tout autre doc
  * [-] dépend d'un déploiement sur `bibdev`
  * [+] accessible dans un déploiement local hors-ligne

2. [Sur le wiki](https://github.com/Bibliome/alvisnlp/wiki)
  * [+] rassemblé aux autres docs
  * [+] facile à éditer
  * [-] mosh

3. [Site web](https://bibliome.github.io/alvisnlp/)
  * [+] rassemblé aux autres docs

**Comment by rbossy** [comment]
https://bibliome.github.io/alvisnlp/

**Comment by jibe-b** [comment]
Il y a un petit soucis visuel avec Firefox

![image](https://user-images.githubusercontent.com/6146483/36094896-4457839c-0ff0-11e8-9535-e2e897f750f2.png)

**Comment by rbossy** [comment]
Oh, joy ! CSS...

**Comment by rbossy** [comment]
@jibe-b et maintenant ?

**Comment by jibe-b** [comment]
4 onglets sur 5 sont ok sur mon écran.

![image](https://user-images.githubusercontent.com/6146483/36105011-d6cee92c-1013-11e8-9729-ded7d3fa96dd.png)

**Comment by jibe-b** [comment]
En revanche, si je change la taille de l'image, le rectangle vert s'ajuste à la taille de l'écran (avec une marge de quelques pixels) mais la barre d'onglet n'obéit pas à la même règle

![image](https://user-images.githubusercontent.com/6146483/36105208-594fd50a-1014-11e8-83d2-9ea5139dd07a.png)

(en réduisant la taille de la fenêtre)

**Comment by rbossy** [comment]
j'abandonne. Un jour je ferai un truc propre avec bs.
