### ISSUE TITLE
AlvisNLP Bibliome Module Factory ................... FAILURE

### ISSUE THREAD

**Issue by PonnakaTITH** [Bibliome/alvisnlp#39]
Bonjour,

En essayant de suivre les instructions, lors de la seconde instruction (mvn clean install), l'installation échoue pour AlvisNLP Bibliome Module Factory. Voici ce qu'affiche à la fin de la console:

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building AlvisNLP Bibliome Module Factory 0.5rc-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for fr.jouy.inra.maiage.bibliome:alvisdb-core:jar:0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AlvisNLP/ML ........................................ SUCCESS [  0.798 s]
[INFO] AlvisNLP Core ...................................... SUCCESS [  6.976 s]
[INFO] AlvisNLP Bibliome Module Factory ................... FAILURE [  0.878 s]
[INFO] alvisnlp-rest ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.957 s
[INFO] Finished at: 2017-11-22T10:46:45+01:00
[INFO] Final Memory: 27M/78M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alvisnlp-bibliome: Could not resolve dependencies for project fr.jouy.inra.maiage.bibliome:alvisnlp-bibliome:jar:0.5rc-SNAPSHOT: Failure to find fr.jouy.inra.maiage.bibliome:alvisdb-core:jar:0.1-SNAPSHOT in http://bibliome.jouy.inra.fr/maven-repository was cached in the local repository, resolution will not be reattempted until the update interval of bibliome has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alvisnlp-bibliome

Pouvez-vous m'aider à résoudre ce problème?

**Comment by rbossy** [comment]
Bonjour,

visiblement certaines dépendances ne sont pas correctement exposées sur notre dépôt Maven. Je vous préviens quand c'est corrigé.

**Comment by rbossy** [comment]
Re,

J'ai mis à jour le dépôt Maven. Est-ce que vous pouvez réessayer, svp? Ce serait peut-être plus sage de nettoyer votre repo Maven local avant de recompiler:

    rm -fr ~/.m2/repository/fr/jouy/inra/maiage/bibliome/

Tenez-moi au courant.

**Comment by PonnakaTITH** [comment]
Re,

Je vous remercie de votre réponse rapide. Les modifications que vous avez apporté ont corrigé l'erreur.

**Comment by mandiayba** [comment]
Bonjour,

si ça peut être utile, il y a également une image docker d'AlvisNLP ici https://hub.docker.com/r/bibliome/alvisengine/

**Comment by rbossy** [comment]
Résolu!

**Comment by rbossy** [comment]
@PonnakaTITH 

Si vous avez des questions, n'hésitez pas à nous contacter `Robert.Bossy@inra.fr`
