### ISSUE TITLE
XLSProjector module (was: .xls to .txt)

### ISSUE THREAD

**Issue by EstelleChaix** [Bibliome/alvisnlp#42]
Je ne suis pas sûre de l'endroit mais bon (cc @mandiayba  ) 

Dans mes étapes de pré-process à AlvisNLP, je transforme mes ressources dont une au format .xls en .txt.  (cf https://github.com/openminted/uc-tdm-AS-E/blob/master/Execution_resources.sh)

J'utilise pour cela le programme inclut dans gnumeric, "[ssconvert](https://help.gnome.org/users/gnumeric/stable/sect-files-ssconvert.html.en)" 

Je ne sais pas s'il faut l'intégrer dans AlvisNLP ou pas (si cela peut être tuilie). Il y a des images dockers qui existent mais je ne sais pas qu'elle est la version , et je ne sais pas trop comment l'utiliser si on réutilise un docker image.

**Comment by rbossy** [comment]
@EstelleChaix 
Est-ce que plutôt ça ne serait pas plus pratique que le projecteur puisse lire directement le `.xls`?

**Comment by EstelleChaix** [comment]
Cela pourrait être effectivement utile. Avec choix des colonnes, cela serait le best. 

Aujourd'hui, je retraite cette donnée là dans mon preprocessing : 

`ssconvert -O 'separator="	" eol=unix quote=' resources/ath_MTI.xls resources/ath_MTI.txt

cat resources/ath_MTI.txt | awk -F"\t" '{print$1"\t"$2"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9;}' | awk -F"\t" '{gsub("ath-","",$3);print$1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9"\t"$10;}' | sort | head -n -1 > resources/ath_MTI_extended.txt `

Après je ne sais pas si ce genre d'opération est faisable sur un .xls.

**Comment by rbossy** [comment]
2f6b982bcaae6a724b07c0a55535ee10d64a3f86

New module: `XLSProjector`

**Comment by rbossy** [comment]
@EstelleChaix 

https://bibliome.github.io/alvisnlp/reference/module/XLSProjector

(déployé sur notre serveur)

**Comment by rbossy** [comment]
@EstelleChaix is this working?

**Comment by rbossy** [comment]
@EstelleChaix, did have the chance to test `XLSProjector` ?

**Comment by EstelleChaix** [comment]
The chance probably, the time ... I don't know :P 

I will try it ASAP

**Comment by rbossy** [comment]
No hurry, just asking.
