### ISSUE TITLE
Problème CaseInsensitive sur Tabular Projector

### ISSUE THREAD

**Issue by EstelleChaix** [Bibliome/alvisnlp#43]
L'option <caseInsensitive> fait des résultats "aléatoires" 

On cherche à normalizer ce fichier : 

Fichier d'entrée 

AP1
AP2
CAL
FWA
FT
AP3
PI
AG
UFO
CO
Co
LD
GA1

Résultat : 
`<caseInsensitive>` inactivée:  

AP1	AT1G69120
AP2	AT4G36920
CAL	AT1G26310
FWA	AT4G25530
**FT	AT1G65480**
AP3	AT3G54340
PI	AT5G20240
AG	AT4G18960
UFO	AT1G30950
**CO	AT5G15840
Co**	
LD	AT4G02560
GA1	AT4G02780

`<caseInsensitive>` Activée:  

AP1	AT1G69120
AP2	AT4G36920
CAL	AT1G26310
FWA	AT4G25530
**FT**	
AP3	AT3G54340
PI	AT5G20240
AG	AT4G18960
UFO	AT1G30950
**CO	
Co**	
LD	AT4G02560
GA1	AT4G02780

pour tester : 
`/bibdev/install/alvisnlp/devel/bin/alvisnlp -inputDir /bibdev/travail/arabidopsis/alvisir2_devel -log plan/alvisnlp.log normalize_genes.plan`

**Comment by rbossy** [comment]
Je ne peux pas éditer le plan.

**Comment by EstelleChaix** [comment]
modifié

**Comment by rbossy** [comment]
Résolu par: https://github.com/Bibliome/bibliome-java-utils/commit/cf1259be6eee1a9735fe5b943706545b481e6886

@EstelleChaix @ldeleger
