### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#47]
## Install procedure for windows

Tested on Windows 10 running in a VirtualBox machine.

1. [Download and install JDK 8 for Windows](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).
2. Set the `JAVA_HOME` environment variable to the JDK directory. Usually something like `C:\Program Files\jdk1.8.0_XXX`, where `XXX` is the update version of the JDK. You can set environment variables through the control panel.
3. [Download and install git for Windows](https://git-scm.com/download/win).
4. [Download](https://maven.apache.org/download.cgi) and [install Maven](https://maven.apache.org/guides/getting-started/windows-prerequisites.html). Installing Maven means extracting the archive in a sensible place like your home or `Program Files`.
5. Set the `Path` environment variable to `%Path%;C:\sensibleplace\apache-maven-3.5.2\bin`.
6. Open a Windows command line window. You may find it by searching for `cmd`.
7. Download and compile AlvisNLP/ML:

```
git clone https://github.com/Bibliome/alvisnlp.git
cd alvisnlp
mvn clean install
```

@ArnaudFerre: could you try this in a native Windows machine?

**Comment by rbossy** [comment]
@ArnaudFerre

Please try:

```
git clone https://github.com/Bibliome/alvisnlp.git    # get source code
cd alvisnlp
git checkout windows-install    # move to the windows install branch
mvn clean install    # compile
mkdir test-install    # create installation directory
./install.ps1 test-install     # install 
./test-install/bin/alvisnlp.ps1 -help    # try alvisnlp
```

If at the command `./install.ps1 test-install` it complains that execution of scripts is not activated, then try the following and try again:

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser     # current user can run scripts
```

**Comment by ArnaudFerre** [comment]
OK, it works. Thanks.
Of course, I just needed to install Maven (tuto [here](http://www.objis.com/formation-java/tutoriel-maven-installation-phases.html#partie1))
My config: Windows 7 Professionnel, 64 bits, Intel Core i7, HP machine.

**Comment by rbossy** [comment]
@ArnaudFerre so you got AlvisNLP/ML help?

**Comment by ArnaudFerre** [comment]
Yes

**Comment by EstelleChaix** [comment]
Hi try it on Windows 8 
At the step 
`./install.ps1 test-install     # install `

I have try on different terminal and it doesn't work: 
Babun and MobaXterm
```
./install.ps1 test-install                                                            
/bin/env: pwsh: No such file or directory
```

On cmd.exe : 
`"." n'est pas reconnue en tant que commande interne`

**Comment by EstelleChaix** [comment]
In cmd.exe , do : 
```
install.bat test-install             
test-install\bin\alvisnlp.bat -help
```   

Note: 
`
test-install\bin\alvisnlp.bat -help `   work also on MobaXterm, but not in Babun

**Comment by rbossy** [comment]
d43dd54a08d73e31e94ae1ece03cf4b576823c8c
