### ISSUE TITLE
TreeTagger for french

### ISSUE THREAD

**Issue by EstelleChaix** [Bibliome/alvisnlp#49]
Problem with the current installation of TreeTagger for French purpose. 
(`<treeTaggerExecutable>..../install/tree-tagger-3.2/bin/tree-tagger</treeTaggerExecutable>`) 
and 
(`<parFile>.../install/tree-tagger-3.2/lib/french-utf8.par</parFile>`)

--
This problem is resolved with : 

With [this](http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-linux-3.2.1.tar.gz)
`<treeTaggerExecutable>tree-tagger-linux-3.2.1/bin/tree-tagger</treeTaggerExecutable>`

and the [french.par](http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/french-par-linux-3.2-utf8.bin.gz)
`<parFile>french.par</parFile>`
 it is ok

**Comment by rbossy** [comment]
@EstelleChaix which one works, which one does not?

**Comment by EstelleChaix** [comment]
I just edit the message to clarify
