### ISSUE TITLE
XMI Serialization

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#51]
Serialize the data structure as UIMA XMI, using a fixed typesystem.

**Comment by rbossy** [comment]
Ongoing work on branch [xmi-issue-51](https://github.com/Bibliome/alvisnlp/tree/xmi-issue-51).

**Comment by rbossy** [comment]
Merged 9879baac062aeffe0d9a977606e8e24bccb808eb to master

**Comment by mandiayba** [comment]
the full path used to localize the input files is recopied in the path to store the output files

for example: `alvisnlp --input /path/to/locatize/input --output /path/to/the/output` will give the result files into `/path/to/the/output//path/to/locatize/input`

could we put the ouput files directly into ` /path/to/the/output` ?

**Comment by rbossy** [comment]
What if your input directory contains:

```
input
  \- foo
    \- file1.xmi
    \- file2.xmi
  \- bar
    \- file1.xmi
```

How do you make the difference between `foo/file1.xmi` and `bar/file1.xmi` ?

**Comment by mandiayba** [comment]
I propose to just consider the part of the input path that is not given by the user.

if  data are into
```
to/path
  \- input
      \- foo
         \- file1.xmi
         \- file2.xmi
     \- bar
        \- file1.xmi
```
and user gives  ```--input path```, we consider the following in the output path

```
input
 \- foo
 \- bar
```

**Comment by rbossy** [comment]
Nope, cannot do that. The information is lost at this point.

However, take a look at the parameter `baseNameId` of `TextFileReader`. Just assume there are no duplicate filenames.

https://bibliome.github.io/alvisnlp/reference/module/TextFileReader#baseNameId

**Comment by rbossy** [comment]
ed876c5a1d0a34ba9807cafd45cc4593f32cd230 adds a `baseNameId` parameter to `XMIImport`.

Merged on *master*.

**Comment by rbossy** [comment]
@mandiayba may I close this?

**Comment by mandiayba** [comment]
yes @rbossy
