### ISSUE TITLE
Accept OMTD command-line options

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#52]
* `--param:PARAM=VALUE` is equivalent to `-alias PARAM VALUE`.
* `--output DIR` is equivalent to `-outputDir DIR`. What if the output is a file and not a directory?
* `--input FILE` is equivalent to `-alias PARAM FILE`. How to guess `PARAM`?

**Comment by rbossy** [comment]
b91582b2ac18e0f70f4dd8cfe4b4ba6a52d4d0ea

**Comment by mandiayba** [comment]
Could you please add ID in order to complete  to the OMTD command.

ID gives the identifier of the component, it is optional. The OMTD will then look like 

```bash
COMMAND ID --input FILE --output DIR --param:PARAM=VALUE
```

**Comment by rbossy** [comment]
So:

`COMMAND` is in fact the `alvisnlp` executable.

`ID` is **not** the OMTD identifier of the component, it is a switch that tells the command which component contained in the docker image is run.

Currently a non-option command-line argument is interpreted as the path to the plan file to execute. Since each component is materialized as a plan file, let's just agree that `ID` is the path of the plan file in the docker image.

Note that `.plan` is not a mandatory extension for the plan file name.

Closing.
