### ISSUE TITLE
output folder of the OMTD components

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/alvisnlp#67]
We must have a flat structure for the folders containing the input/output files. That is required for the OMTD Galaxy and workflow-service to handle the results.

this issue is related to issue #51

see also the comments from here https://github.com/openminted/omtd-docker-specification/issues/2#issuecomment-375707398

**Comment by reckart** [comment]
Just to mention that the required parameters are currently only available in DKPro Core 1.9.1-SNAPSHOT. I am planning to do a 1.9.1 release soonish - need to check that the metadata of DKPro Core meets the latest OMTD requirements and that the OMTD Maven Plugin are released first.

**Comment by rbossy** [comment]
@reckart wrong thread?

**Comment by reckart** [comment]
@rbossy not sure. I had the impression that the discussion from the docker spec branched out to here seeing this issue being linked there when we discussed that Alvis components should be reading the type system as well.

**Comment by rbossy** [comment]
Thanks for clearing that @reckart. The typesystem support is notified in another issue (#68).

This one will be closed after some testing embargo...

**Comment by rbossy** [comment]
@mandiayba ist this working properly now?

**Comment by mandiayba** [comment]
yes   @rbossy
