### ISSUE TITLE
modify the XMIImport to load the typesystem.xml

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/alvisnlp#68]
check here the reason https://github.com/openminted/omtd-docker-specification/issues/2#issuecomment-375719405

**Comment by rbossy** [comment]
Atm `XMIImport` ignores `typesystem.xml` and annotations it does not understand. I will keep this issue open until `XMIImport` reads `typesystem.xml` and the annotations described in it.

**Comment by rbossy** [comment]
Support for `XMIImport` has been dropped.
