### ISSUE TITLE
Cleaner YateaExtractor output

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisnlp#86]
Modules `YateaExtractor` and `TomapTrain` call YaTeA and create an output/working directory specified by `workingDir`. The problem is that the useful files are buried in this directory tree.

Proposal create a parameter that specifies where to write the *real* yatea output file.

**Comment by rbossy** [comment]
243d963 in branch `yatea-file`, the modules `YateaExtractor` and `TomaTrain` have two additional parameters:

* `xmlTermsFile`: location of the XML YaTeA output
* `termListFile`: location of the text YaTeA output

The modules still use `workingDir` for the YaTeA working directory but its usage is **deprecated**. If `workingDir` is not set the modules use a directory in the temporary directory.

**Comment by ldeleger** [comment]
It works, but only if the given folder exists. Would be nice to create the folder if it doesn't exist.

**Comment by rbossy** [comment]
Done in 49e4834d836990758318dcd1c49a5e82c91b4056

And deployed.

**Comment by rbossy** [comment]
@ldeleger good?

**Comment by rbossy** [comment]
@ldeleger Closing after months without complaints...
