### ISSUE TITLE
XSLT stylesheet "old2newplan.xslt" does not support xml entities

### ISSUE THREAD

**Issue by ldeleger** [Bibliome/alvisnlp#88]
old2newplan.xslt cannot process Alvis plans containing xml entities (e.g. &corpus;)

**Comment by rbossy** [comment]
This is how it should be used:

```
alvisnlp -entity corpus CORPUS -entity batch BATCH
        -writePlan -docTransformer old2newplan.xslt old.plan >new.plan
```

Unfortunately there is no way to prevent the replacement of occurrences of entities with their definitions (see #89). So you're bound to put entities back in place:

```
sed -e 's,CORPUS,\&corpus;,g' -e 's,BATCH,\&batch;,g' new.plan >correct.plan
```

@ldeleger

**Comment by rbossy** [comment]
Rejected because custom entities will be dropped: #89
