### ISSUE TITLE
More test checks (was: tees tests failing for bad reason)

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/alvisnlp#92]
After updating tees, the tests are finishing correctly but the outputs are different from the ones ([TP](https://github.com/Bibliome/alvisnlp/blob/tees-updates/alvisnlp-test/tees/TP.txt), [FN](https://github.com/Bibliome/alvisnlp/blob/tees-updates/alvisnlp-test/tees/FN.txt), [FP](https://github.com/Bibliome/alvisnlp/blob/tees-updates/alvisnlp-test/tees/FP.txt)) defined for the validation of the results. Can replace them, but not sure if have to do so ?

**Comment by mandiayba** [comment]
Then, a solution may be to change the manner we check the outputs : why not just focus on an verification of some mandatory elements and specific patterns (ie., presence of non-empty output files, presence of some predictions in the files) ?

**Comment by rbossy** [comment]
That would be better. We could just start checking that the files are not empty...

**Comment by rbossy** [comment]
4051136a8e6bbf29472c1122da745c096e9ba71b introduces the following checks:

`count-lines FILE N` : check that the number of **lines** in `FILE` (in the test working directory) is greateer or equal than `N`.

`count-bytes FILE N` : check that the number of **bytes** in `FILE` (in the test working directory) is greateer or equal than `N`.

`search-pattern FILE REGEXP` : search in `FILE` (in the test working directory) for `PATTERN` (PCRE).

`check-file` and `check-file-sorted` are still available.

@mandiayba 
78d4a3877cdefa598e67166f91377d4b5be5548d modifies the TEES test, but I didn't run the test.

**Comment by rbossy** [comment]
@mandiayba may I close this issue?

**Comment by mandiayba** [comment]
Yes, you may close the issue, thx
