### ISSUE TITLE
GeniaTagger / TreeTagger Mapping 

### ISSUE THREAD

**Issue by ldeleger** [Bibliome/alvisnlp#97]
Add the following transformations :

- "HYPH" --> ":"
- "AFX" --> "NN" (ça c'est plus douteux, je crois que j'avais trouvé que pas mal de AFX étaient mal taggés et correspondaient à des NN)

**Comment by ldeleger** [comment]
Also, there is an error:

if (lemma.equals("be") && pos.startsWith("VB")) {
return "VV" + pos.substring(2);
}

should be:

if (**!** lemma.equals("be") && pos.startsWith("VB")) {
return "VV" + pos.substring(2);
}

**Comment by rbossy** [comment]
Last commit (571cdf7b47f0fcd1d56ec4091af8b2d8fb1f2199) does the following:

```
		if (lemma.equals("have") && pos.startsWith("VB")) {
			return "VH" + pos.substring(2);
		}
		if (!lemma.equals("be") && pos.startsWith("VB")) {
			return "VV" + pos.substring(2);
		}
		if (pos.startsWith("NNP")) {
			return "NP" + pos.substring(3);
		}
		if (pos.equals("HYPH")) {
			return ":";
		}
		if (pos.equals("AFX")) {
			return "NN";
		}
		if (pos.startsWith("PRP")) {
			return "PP" + pos.substring(3);
		}
		if (pos.equals(".")) {
			return "SENT";
		}
		return pos;
```

@ldeleger review pls

**Comment by ldeleger** [comment]
oui ça a l'air bien
